# Name of the workflow
name: NPM Publish

# Run on every commit tag which begins with "v" (e.g., "v0.1.4")
on:
  push:
    tags:
      - "v*"
env:
  NODE_VERSION: 20
  
# Automatically create a GitHub Release, with release details specified (the relevant commits)
jobs:
  release:
    name: "Release & Publish"
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{env.NODE_VERSION}}
          cache: 'yarn' 
      
      - name: Build
        run: yarn install && yarn build       

      - name: Meandao Release & Publish Toolkit
        uses: mean-dao/npm-publish-toolkit@v17.1
        with:
          access: public
          npm_token: ${{ secrets.NPM_TOKEN }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
          gchat_webhook: ${{ secrets.GOOGLE_CHAT_WEBHOOK }}